// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUDq9atuWcXyaAZlE2zYNIwGryefZ0co',
    appId: '1:60746230288:web:716aa8fcff25e595077895',
    messagingSenderId: '60746230288',
    projectId: 'cats-app-de6f9',
    authDomain: 'cats-app-de6f9.firebaseapp.com',
    storageBucket: 'cats-app-de6f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIoBfY48pnNWz6Onxj_gl6ySLSixVxwWw',
    appId: '1:60746230288:android:79da474db9775454077895',
    messagingSenderId: '60746230288',
    projectId: 'cats-app-de6f9',
    storageBucket: 'cats-app-de6f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqfcZlKb9I-LLit9LFe56VndZlt1V6hVc',
    appId: '1:60746230288:ios:7f5a2c74854f74f8077895',
    messagingSenderId: '60746230288',
    projectId: 'cats-app-de6f9',
    storageBucket: 'cats-app-de6f9.appspot.com',
    iosBundleId: 'com.example.myCats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqfcZlKb9I-LLit9LFe56VndZlt1V6hVc',
    appId: '1:60746230288:ios:639c0a0e791a1926077895',
    messagingSenderId: '60746230288',
    projectId: 'cats-app-de6f9',
    storageBucket: 'cats-app-de6f9.appspot.com',
    iosBundleId: 'com.example.myCats.RunnerTests',
  );
}
